spring.application.name=fotova-creation-mcp-acc


####### MYSQL DATABASE CONNEXION ######
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/fotova_db_dev
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

##### MCP CONFIG #######
spring.ai.mcp.server.name=mcp-fotova
spring.ai.mcp.server.type=async
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/sse/message
spring.ai.mcp.server.version=1.0.0


logging.level.io.modelcontextprotocol=TRACE
logging.level.org.springframework.ai.mcp=TRACE

